// Code generated by goctl. DO NOT EDIT.
package types

type UserCreateReq struct {
	Username string `json:"username"`
	Name     string `json:"name"`
	Gender   string `json:"gender"`
}

type UserReply struct {
	Id        int64  `json:"id"`
	Username  string `json:"username"`
	Name      string `json:"name"`
	Gender    string `json:"gender"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
