// Code generated by goctl. DO NOT EDIT!
// Source: log.proto

package server

import (
	"context"

	"zero-strange/service/broker/rpc/internal/logic"
	"zero-strange/service/broker/rpc/internal/svc"
	"zero-strange/service/broker/rpc/types/log"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	log.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) LogLogin(ctx context.Context, in *log.LoginReq) (*log.LoginInfoReply, error) {
	l := logic.NewLogLoginLogic(ctx, s.svcCtx)
	return l.LogLogin(in)
}
